name: Merge PR to Master

on:
  workflow_run:
    workflows:
      - Create PR to Master
    types:
      - completed

jobs:
  automerge:
    if: ${{ github.event.label.name == 'automerge' }}
    runs-on: ubuntu-latest

    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.3"
        permissions:
          contents: write
        env:
          GITHUB_TOKEN: "${{ secrets.WORKFLOW_TOKEN }}"
          MERGE_LABELS: "automerge"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_REQUIRED_APPROVALS: "0"
          UPDATE_METHOD: "rebase"
          LOG: "DEBUG"